### ISSUE TITLE
[BUG] fix error "Inefficient Regular Expression Complexity in chalk/ansi-regex"

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#124]
**What is the bug?**
We have a security issue for this repo https://github.com/opensearch-project/opensearch-dashboards-functional-test/security/dependabot/1

**Comment by tianleh** [comment]
cc @Tengda-He

**Comment by Tengda-He** [comment]
once this PR in OSD is merged, this bug should be fixed automatically https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1320

**Comment by tianleh** [comment]
issue still exists https://github.com/opensearch-project/opensearch-dashboards-functional-test/security/dependabot
