### ISSUE TITLE
[BUG] Visbuilder basic.spec.js failed

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/opensearch-dashboards-functional-test#1322]
### What is the bug?

The UI component is overlapped and it seems the interaction is not correct as after clicking the button, the axis form disappeared.

### Overlapped
<img width="247" alt="image" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/13493605/80bc21d9-1c3a-4578-9898-5f86611022ca">

### Disappeared
<img width="284" alt="image" src="https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/13493605/1c3ba5c9-eabf-43b4-839b-5d1d1991be84">

### The video

https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/13493605/4a65c754-c6e4-4a7f-9a57-4cf512ef8133

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
@SuZhou-Joe was this fixed with #1371? Can it be closed?

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by SuZhou-Joe** [comment]
Nope, in main it still failed. @ashwin-pc Could you please take a look? This failure happens only in main branch.
